### PR TITLE
matrixreg + csvreg + code duplication

### PR DESCRIPTION
**Pull request by vincentarelbundock**
This PR works, but it's probably not ready to be merged yet. I just want to let you know about some stuff I've been working on.

- Code duplication 1: screenreg/htmlreg/texreg all use basically the same code to extract information from models and create an ``output.matrix``.
- Code duplication 2: creating stars notes is pretty confusing, and there is a lot of code duplication across ``*reg`` functions.
- Desired feature 1: https://github.com/leifeld/texreg/issues/23 suggests different output formats (e.g., xlsx or csv)

Solution:

- ``matrixreg``: Consolidate the table building code in a single function that produces a clean character matrix, with stars, gof and everything.
- The other ``*reg`` functions essentially become wrappers around ``matrixreg`` to take care of printing, but not much else. They are "writers"
- Allow users to call ``matrixreg`` and do whatever they want with the output.
- Build other "writers". This PR already has a ``csvreg`` function. Example output below.

Implementation detail: Some of the intermediary objects created while building the ``output.matrix`` are useful later on for printing. That useful information is encoded in attributes of the output from ``matrixreg``. The argument is ``include.attributes = FALSE`` by default, but switched to ``include.attributes = TRUE`` when called internally by another ``*reg`` function which needs access to those attributes.

```
> library(texreg)
> url = 'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/HistData/Guerry.csv'
> dat = read.csv(url, stringsAsFactors=FALSE)
> models = list()
> models[['All Donations']] = lm(Literacy ~ Donations + Region, dat)
> models[['Clergy Donations']] = lm(Literacy ~ Donation_clergy + Region, dat)
> matrixreg(models, stars=c(.44, .1, .01, .5), include.attributes = TRUE)
      [,1]              [,2]            [,3]
 [1,] ""                "All Donations" "Clergy Donations"
 [2,] "(Intercept)"     "29.06 ***"     "32.69 ***"
 [3,] ""                "(3.50)   "     "(4.10)   "
 [4,] "Donations"       "-0.00 *  "     "         "
 [5,] ""                "(0.00)   "     "         "
 [6,] "RegionE"         "29.51 ***"     "27.92 ***"
 [7,] ""                "(3.96)   "     "(4.01)   "
 [8,] "RegionN"         "28.34 ***"     "25.15 ***"
 [9,] ""                "(3.89)   "     "(4.07)   "
[10,] "RegionS"         " 4.40 *  "     " 4.97 *  "
[11,] ""                "(4.05)   "     "(3.86)   "
[12,] "RegionW"         " 2.84 .  "     " 0.03    "
[13,] ""                "(3.95)   "     "(3.91)   "
[14,] "Donation_clergy" "         "     "-0.12 ** "
[15,] ""                "         "     "(0.05)   "
[16,] "R^2"             " 0.60    "     " 0.61    "
[17,] "Adj. R^2"        " 0.58    "     " 0.59    "
[18,] "Num. obs."       "85       "     "85       "
[19,] "RMSE"            "11.35    "     "11.16    "
attr(,"ci")
[1] FALSE FALSE
attr(,"ci.test")
[1] 0
attr(,"gof.names")
[1] "R^2"       "Adj. R^2"  "Num. obs." "RMSE"
attr(,"mod.names")
[1] "All Donations"    "Clergy Donations"
>
```

And the CSV file looks like this:

```
> csvreg(models, stars=c(.44, .1, .01, .5), ci.force=c(TRUE, FALSE),
+        file='~/Downloads/test.csv', caption = 'Statistical Models -- Oh yeah!',
+        custom.note = 'some text')
>
```

csvreg

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
One major problem currently is that stars don't appear *in the table* with ``htmlreg``.

**Comment by leifeld** [comment]
This sounds like a useful enhancement. I'm always in favor of code changes that fix duplication issues.

I'm not sure what you mean by "stars don't appear _in the table_ with `htmlreg`". They are typeset as `<sup>*</sup>`, and that's happening in the table. Or are you talking about the note?

**Comment by vincentarelbundock** [comment]
I just did a test locally, and it didn't look like stars were shown next to coefficients. Will look again later

**Comment by vincentarelbundock** [comment]
@leifeld I think this works now. 

Locally, I get no errors or warnings, but TravisCI breaks on a latex-related issue.

I also added a barebones function to export tables directly to Word documents (useful for me, since I'm collaborating with Word-only folks at the moment).

Be aware that this is a significant refactor. If/when you decide to merge, I can stick around and monitor my mentions carefully. Just ping me or shoot me an email and I'll help debug/fix any problem related to this PR.

**Comment by leifeld** [comment]
Wow, these are quite a few changes. Thanks for this. It may take me a few days to review them as I am currently on a conference round-trip. Sorry about that. I'll get back to you.

**Comment by vincentarelbundock** [comment]
Yeah, I'm sorry about that. I'm aware that reviewing this kind of PR is quite a burden. I'm hoping it'll be worth it in the end.

**Comment by leifeld** [comment]
Sorry it took me super long. There are still a few issues, but I'll try to tackle them after accepting the PR.

**Comment by vincentarelbundock** [comment]
hehe, I had completely forgotten about this. Surprised to see it merged all in one go :)

Let me know if you'd like me to work on anything to make the transition smoother (though, for transparency, I should say that I am overcommitted these days, so it might take a little while).

**Pull request merged**
