### PR TITLE
closes issue #64

### PR DESCRIPTION
**Pull request by czucca**
substituted two lines in order to fix the bug for which the `reorder.gof` argument was giving an error. Added lines 77-83 on `texreg.R`.

### CODE REVIEW

**Comment by leifeld** [comment]
Thanks, that looks good. Have you tested the code? If so, I'll approve and merge.

**Comment by czucca** [comment]
yes all tested and good to go!

**Comment by leifeld** [comment]
Cool. Do you want to squash and merge? ;)

**Comment by czucca** [comment]
yeahh! always :)

**Pull request merged**
