### PR TITLE
Closes Issue #7

### PR DESCRIPTION
**Pull request by czucca**
-Modified function `ciforce`  in `internal.R` to enable the display of confidence intervals calculated from a t-distribution. 

-Enabled the tdistribution to be calculated on the models of family lm and glm. 

- the usage of the `ci.force =`  argument in  `texreg`, `screenreg` etc, changed from logical to character. 
before: `ci.force = TRUE`, `ci.force = FALSE`
now: `ci.force = "null"`, `ci.force = "ndistr"`, `ci.force = "tdistr`

-documentation modified accordingly. 
-break and error message showed if t distribution not available for the required model class.

### CODE REVIEW

**Comment by czucca** [comment]
here there is a problem in the vignette. It concerns the fact that I changed `extract.lm`. At this point, before finding a way to fix it. It would be better to see if you approve this change or if you want me to do it differently (I think there is a margin for improvement).

**Comment by leifeld** [comment]
@czucca: I've been thinking about this one for a few weeks now. I tend to say that adding additional slots to `texreg` objects to let the package compute additional quantities is not the right direction to take. `texreg` is a package for reporting results, not for actually doing statistics. I don't think we should go out of our way to accommodate the t-distribution. I can see how it would be nice to have, especially since we already have the z-score method, but that one does not require additional data to be stored just for that purpose. If you don't have any strong feelings about this, I would suggest closing this PR and associated issue. What do you think?

**Comment by czucca** [comment]
Hi Philip, 

Yes, I agree entirely with you. It is not good to add additional slots to texreg, but also, to keep this one would have required to modify most of the existing extract functions to add the residuals df etc. If somebody needs to display results from a  t-distr they can still override coefficients on texreg after calculating them manually.

**Comment by leifeld** [comment]
Glad we agree. Sorry for the time you wasted on this. I'll close it then.

**Comment by czucca** [comment]
no worries :)

**Pull request closed without merging**
