### PR TITLE
avoid partial matching

### PR DESCRIPTION
**Pull request by helix123**
addresses #18 for extract.plm (other functions likely also affected)

### CODE REVIEW

**Comment by helix123** [comment]
Thank you for merging it pull request in!
I believe increasing the version number and date should be left to the pkg's maintainer.
`coef()` is just returns `object$coefficients` (for `stats:::coef.default()`), so calling it a few times does not impose a significant performance penalty for this type of application.

There are more model types affected by partial matching, but maybe someone else will pick up on those!

**Comment by leifeld** [comment]
OK, thanks! I was used to doing it the CRAN way, which means every single commit should have a new version number. But I'm getting used to GitHub...

Can you elaborate on why partial matching is a problem in the context of an `extract` function?

**Comment by helix123** [comment]
Well, it is ugly for those having the option about the warning enabled. But then again, it could also shield from errors (e.g. typing when the internals of an object change, e.g. renaming from "coefficient" to "coefficients"). It's just better to use well defined extraction functions (but for `residuals()` the behaviour depends on na.action, so better don't use it for the # of obs used in model estimation and use object$residuals instead).

**Comment by leifeld** [comment]
Thanks, that's helpful. I will leave this issue open as long as there are other places in the code left that need to be updated. In case you want to contribute to that, please by all means feel free to do so. But no pressure, of course.

**Pull request merged**
