### PR TITLE
fails if omit leads to only one remaining coef?

### PR DESCRIPTION
**Pull request by MatthieuStigler**
Hi

I think if your `omit.coef`expression removea all but one coefficient, this will create an issue, see below. Comes from the `m[idx,]` not having `drop = FALSE`?

``` r
library(devtools)
install_github("leifeld/texreg")
#> Skipping install of 'texreg' from a github remote, the SHA1 (e599c4b2) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(texreg)
#> Version:  1.36.24
#> Date:     2018-09-07
#> Author:   Philip Leifeld (University of Glasgow)
#> 
#> Please cite the JSS article in your publications -- see citation("texreg").
example(texreg, echo = FALSE)

texreg(list(model.1, model.2), booktabs = TRUE, dcolumn = TRUE,
       omit.coef = "SexFemale|age")
#> Error in `rownames<-`(x, value): attempt to set 'rownames' on an object with no dimensions
```

<sup>Created on 2018-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

After fix:

``` r
library(devtools)
install_github("MatthieuStigler/texreg")
#> Downloading GitHub repo MatthieuStigler/texreg@master
#> from URL https://api.github.com/repos/MatthieuStigler/texreg/zipball/master
#> Installing texreg
#> '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
#>   --quiet CMD INSTALL  \
#>   '/tmp/RtmpRHcuDi/devtools370a4bcf0773/MatthieuStigler-texreg-d9540b7'  \
#>   --library='/home/matifou/R/x86_64-pc-linux-gnu-library/3.4'  \
#>   --install-tests
#> 
library(texreg)
#> Version:  1.36.24
#> Date:     2018-09-07
#> Author:   Philip Leifeld (University of Glasgow)
#> 
#> Please cite the JSS article in your publications -- see citation("texreg").
example(texreg, echo = FALSE, verbose = FALSE)

texreg(list(model.1, model.2), booktabs = TRUE, dcolumn = TRUE,
       omit.coef = "SexFemale|age")
#> 
#> \usepackage{booktabs}
#> \usepackage{dcolumn}
#> 
#> \begin{table}
#> \begin{center}
#> \begin{tabular}{l D{.}{.}{13.8} D{.}{.}{13.8} }
#> \toprule
#>  & \multicolumn{1}{c}{Model 1} & \multicolumn{1}{c}{Model 2} \\
#> \midrule
#> (Intercept)          &   16.76^{***} &   17.71^{***} \\
#>                      &   (0.80)      &   (0.83)      \\
#> \midrule
#> AIC                  &  455.00       &  447.51       \\
#> BIC                  &  465.66       &  460.78       \\
#> Log Likelihood       & -223.50       & -218.76       \\
#> Num. obs.            &  108          &  108          \\
#> Num. groups: Subject &   27          &   27          \\
#> \bottomrule
#> \multicolumn{3}{l}{\scriptsize{$^{***} p <0.001$; $^{**} p <0.01$; $^{*} p <0.05$}}
#> \end{tabular}
#> \caption{Statistical models}
#> \label{table:coefficients}
#> \end{center}
#> \end{table}
```

<sup>Created on 2018-10-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by czucca** [comment]
Hi Matthieu, 

If you check in the main page Philip says

"I will only consider pull requests that address an issue described in the issue tracker, so please create an issue first before fixing it."

[https://github.com/leifeld/texreg]

The issue referenced here is not related to your PR. 

Also, it would be helpful if you could explain in plain words what did you change and where in order to make faster to review your PR. Just a suggestion. 

I personally do not consider this a as bug, and I do not see it as a priority, but it is up to Philip. 

Hope this helps.

**Comment by MatthieuStigler** [comment]
oh sorry aout that, I opened issue #103 , where I detail change needed

**Comment by czucca** [comment]
Hi Philip and Matthieu, 

I took care of the conflicts. If Matthieu approves the commit, Philip you can check again and eventually merge. 

Hope this helps, 
C.

**Comment by leifeld** [comment]
That's great, even better! I'll approve and merge it now!

**Pull request merged**
